Trying to test extension
::

    $ py.test tests/test_dummy.py
    re-exec with libfaketime dependencies
    ============================================== test session starts ===============================================
    platform linux -- Python 3.5.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
    rootdir: /home/jpic/env/src/epo, inifile:
    plugins: mock-1.2, logging-2015.11.4, cov-2.4.0, asyncio-0.5.0
    collected 1 items

    tests/test_dummy.py F

    ==================================================== FAILURES ====================================================
    ______________________________________________ test_create_job_logs ______________________________________________

    thing = <module 'jenkins_epo' from '/home/jpic/env/src/epo/jenkins_epo/__init__.py'>, comp = 'dummy'
    import_path = 'jenkins_epo.dummy'

        def _dot_lookup(thing, comp, import_path):
            try:
    >           return getattr(thing, comp)
    E           AttributeError: module 'jenkins_epo' has no attribute 'dummy'

    /usr/lib64/python3.5/unittest/mock.py:1049: AttributeError

    During handling of the above exception, another exception occurred:

    args = (), keywargs = {}, extra_args = [], entered_patchers = []
    exc_info = (<class '_gdbm.error'>, error(11, 'Resource temporarily unavailable'), <traceback object at 0x7f97cb7dbe08>)
    patching = <unittest.mock._patch object at 0x7f97c9dc4a90>

        @wraps(func)
        def patched(*args, **keywargs):
            extra_args = []
            entered_patchers = []

            exc_info = tuple()
            try:
                for patching in patched.patchings:
    >               arg = patching.__enter__()

    /usr/lib64/python3.5/unittest/mock.py:1149:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    /usr/lib64/python3.5/unittest/mock.py:1205: in __enter__
        self.target = self.getter()
    /usr/lib64/python3.5/unittest/mock.py:1375: in <lambda>
        getter = lambda: _importer(target)
    /usr/lib64/python3.5/unittest/mock.py:1062: in _importer
        thing = _dot_lookup(thing, comp, import_path)
    /usr/lib64/python3.5/unittest/mock.py:1051: in _dot_lookup
        __import__(import_path)
    jenkins_epo/dummy.py:3: in <module>
        from .extensions import (
    jenkins_epo/extensions.py:27: in <module>
        from .github import GITHUB, ApiNotFoundError
    jenkins_epo/github.py:29: in <module>
        from .cache import CACHE
    jenkins_epo/cache.py:133: in <module>
        CACHE = FileCache()
    jenkins_epo/cache.py:69: in __init__
        self.open()
    jenkins_epo/cache.py:83: in open
        self.storage = shelve.open(SETTINGS.CACHE_PATH, mode)
    /usr/lib64/python3.5/shelve.py:243: in open
        return DbfilenameShelf(filename, flag, protocol, writeback)
    /usr/lib64/python3.5/shelve.py:227: in __init__
        Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    file = '.epo-cache', flag = 'r', mode = 438

        def open(file, flag='r', mode=0o666):
            """Open or create database at path given by *file*.

            Optional argument *flag* can be 'r' (default) for read-only access, 'w'
            for read-write access of an existing database, 'c' for read-write access
            to a new or existing database, and 'n' for read-write access to a new
            database.

            Note: 'r' and 'w' fail if the database doesn't exist; 'c' creates it
            only if it doesn't exist; and 'n' always creates a new database.
            """
            global _defaultmod
            if _defaultmod is None:
                for name in _names:
                    try:
                        mod = __import__(name, fromlist=['open'])
                    except ImportError:
                        continue
                    if not _defaultmod:
                        _defaultmod = mod
                    _modules[name] = mod
                if not _defaultmod:
                    raise ImportError("no dbm clone found; tried %s" % _names)

            # guess the type of an existing database, if not creating a new one
            result = whichdb(file) if 'n' not in flag else None
            if result is None:
                # db doesn't exist or 'n' flag was specified to create a new db
                if 'c' in flag or 'n' in flag:
                    # file doesn't exist and the new flag was used so use default type
                    mod = _defaultmod
                else:
                    raise error[0]("need 'c' or 'n' flag to open new db")
            elif result == "":
                # db type cannot be determined
                raise error[0]("db type could not be determined")
            elif result not in _modules:
                raise error[0]("db type is {0}, but the module is not "
                               "available".format(result))
            else:
                mod = _modules[result]
    >       return mod.open(file, flag, mode)
    E       _gdbm.error: [Errno 11] Resource temporarily unavailable

    /usr/lib64/python3.5/dbm/__init__.py:94: error
    ============================================ 1 failed in 0.36 seconds ============================================
    Exception ignored in: <bound method FileCache.__del__ of <jenkins_epo.cache.FileCache object at 0x7f97cb7cfbe0>>
    Traceback (most recent call last):
      File "/home/jpic/env/src/epo/jenkins_epo/cache.py", line 130, in __del__
      File "/home/jpic/env/src/epo/jenkins_epo/cache.py", line 92, in close
      File "/home/jpic/env/src/epo/jenkins_epo/cache.py", line 104, in save
    AttributeError: 'FileCache' object has no attribute 'storage'